// <auto-generated />
using System;
using DocsStorageWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DocsStorageWebApi.Migrations
{
    [DbContext(typeof(AppDdContext))]
    partial class AppDdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocsStorageWebApi.Models.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("DocumentName")
                        .IsRequired();

                    b.Property<string>("DocumentStorageID")
                        .IsRequired();

                    b.Property<string>("Exstension")
                        .IsRequired();

                    b.Property<DateTime>("LoadDate");

                    b.HasKey("DocumentID");

                    b.HasIndex("DocumentStorageID")
                        .IsUnique();

                    b.HasIndex("DocumentID", "DocumentName");

                    b.ToTable("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
